config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  resources :operations
  resources :equipments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  validates :name, :equipment_type, presence: true
  has_many :operation, dependent: :delete_all
  accepts_nested_attributes_for :operation
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :equipment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: %i[ show edit update destroy ]

  # GET /equipment or /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/1 or /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment or /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to equipment_url(@equipment), notice: "Equipment was successfully created." }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1 or /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to equipment_url(@equipment), notice: "Equipment was successfully updated." }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1 or /equipment/1.json
  def destroy
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: "Equipment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipment_params
      params.require(:equipment).permit(:name, :equipment_type, :model, :description)
    end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  before_action :set_equipment, only: %i[ show edit update destroy ]

  # GET /equipments or /equipments.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipments/1 or /equipments/1.json
  def show
  end

  # GET /equipments/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipments/1/edit
  def edit
  end

  # POST /equipments or /equipments.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to equipment_url(@equipment), notice: "Equipment was successfully created." }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipments/1 or /equipments/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to equipment_url(@equipment), notice: "Equipment was successfully updated." }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipments/1 or /equipments/1.json
  def destroy
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipments_url, notice: "Equipment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipment_params
      params.require(:equipment).permit(:name, :equipment_type, :model, :description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]

  # GET /operations or /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1 or /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:name, :code, :last_check, :next_check, :equipment_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/equipment/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Equipment</h1>

<div id="equipment">
  <% @equipment.each do |equipment| %>
    <%= render equipment %>
    <p>
      <%= link_to "Show this equipment", equipment %>
    </p>
  <% end %>
</div>

<%= link_to "New equipment", new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New equipment</h1>

<%= render "form", equipment: @equipment %>

<br>

<div>
  <%= link_to "Back to equipment", equipment_index_path %>
</div>

app/views/equipments/_equipment.html.erb
<div id="<%= dom_id equipment %>">
  <p>
    <strong>Name:</strong>
    <%= equipment.name %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= equipment.equipment_type %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= equipment.model %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= equipment.description %>
  </p>

</div>

app/views/equipments/_form.html.erb
<%= form_with(model: equipment) do |form| %>
<% if equipment.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

    <ul>
      <% equipment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div>
  <%= form.label :name, style: "display: block" %>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.label :equipment_type, style: "display: block" %>
  <%= form.number_field :equipment_type %>
</div>

<div>
  <%= form.label :model, style: "display: block" %>
  <%= form.text_field :model %>
</div>

<div>
  <%= form.label :description, style: "display: block" %>
  <%= form.text_field :description %>
</div>

<div>
  <%= form.submit %>
</div>
<% end %>

app/views/equipments/edit.html.erb
<h1>Editing equipment</h1>


<%= render "form", equipment: @equipment %>

<br>

<div>
  <%= link_to "Show this equipments", @equipment %> |
  <%= link_to "Back to equipments", equipments_path %>
</div>

app/views/equipments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-3xl font-bold">
  Equipment
</h1>
<div id="equipment">
  <% @equipment.each do |equipment| %>
    <%= render equipment %>
    <p>
      <%= link_to "Show this equipments", equipment %>
    </p>
  <% end %>
</div>

<%= link_to "New equipments", new_equipment_path %>

app/views/equipments/new.html.erb
<h1>New equipment</h1>

<%= render "form", equipment: @equipment %>

<br>

<div>
  <%= link_to "Back to equipments", equipments_path %>
</div>

app/views/equipments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @equipment %>

<div>
  <%= link_to "Edit this equipments", edit_equipment_path(@equipment) %> |
  <%= link_to "Back to equipments", equipments_path %>

  <%= button_to "Destroy this equipments", @equipment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Epr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="w-full">
    <nav class="flex justify-center space-x-4">
      <%= link_to 'Equipments', equipments_path, { :class => "font-bold px-3 py-2 text-slate-700 rounded-lg hover:bg-slate-100 hover:text-slate-900"} %>
      <a href="/" class="font-bold px-3 py-2 text-slate-700 rounded-lg hover:bg-slate-100 hover:text-slate-900">Journal</a>
      <a href="/" class="font-bold px-3 py-2 text-slate-700 rounded-lg hover:bg-slate-100 hover:text-slate-900">Stuff</a>
    </nav>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>

  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="flex space-x-4">
    <blockquote class="text-2xl font-semibold italic text-center text-slate-900">
    When you need to
    <span class="before:block before:absolute before:-inset-1 before:-skew-y-3 before:bg-pink-500 relative inline-block">
    <span class="relative text-white">managed</span>
  </span>
    office
    <span class="before:block before:absolute before:-inset-1 before:-skew-y-3 before:bg-pink-500 relative inline-block">
    <span class="relative text-white">equipment</span>
  </span>
  </blockquote>
</div>

</div>

app/views/operations/_form.html.erb
<%= form_with(model: operation) do |form| %>
  <% if operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :last_check, style: "display: block" %>
    <%= form.time_field :last_check %>
  </div>

  <div>
    <%= form.label :next_check, style: "display: block" %>
    <%= form.time_field :next_check %>
  </div>

  <div>
    <%= form.label :equipment_id, style: "display: block" %>
    <%= form.text_field :equipment_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <p>
    <strong>Name:</strong>
    <%= operation.name %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= operation.code %>
  </p>

  <p>
    <strong>Last check:</strong>
    <%= operation.last_check %>
  </p>

  <p>
    <strong>Next check:</strong>
    <%= operation.next_check %>
  </p>

  <p>
    <strong>Equipment:</strong>
    <%= operation.equipment_id %>
  </p>

</div>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @operation %> |
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Operations</h1>

<div id="operations">
  <% @operations.each do |operation| %>
    <%= render operation %>
    <p>
      <%= link_to "Show this operation", operation %>
    </p>
  <% end %>
</div>

<%= link_to "New operation", new_operation_path %>

app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @operation %>

<div>
  <%= link_to "Edit this operation", edit_operation_path(@operation) %> |
  <%= link_to "Back to operations", operations_path %>

  <%= button_to "Destroy this operation", @operation, method: :delete %>
</div>